# Generated by Django 4.1.10 on 2024-03-07 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REJECTED", "Rejected"),
                            ("ACCEPTED", "Accepted"),
                            ("IN PROGRESS", "In Progress"),
                        ],
                        default="IN PROGRESS",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CT",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trial_name", models.CharField(max_length=255)),
                ("trial_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EAPDossier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=255)),
                ("enrollment_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("abbreviation", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "initial_consult_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.contact",
                    ),
                ),
                (
                    "medical_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.medicalcondition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Physician", "Physician"),
                            ("Pharmacist", "Pharmacist"),
                            ("PN", "PN"),
                        ],
                        max_length=50,
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                (
                    "medical_license_number",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hospital"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_person",
                        to="api.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Landing Page Submission", "Landing Page Submission"),
                            ("Call", "Call"),
                            ("Email", "Email"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_date", models.DateTimeField()),
                ("reminder_date", models.DateTimeField()),
                ("no_show", models.BooleanField()),
                ("notes", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
                (
                    "patient_navigator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.professional",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_person",
                to="api.person",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="physician",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.professional",
            ),
        ),
        migrations.CreateModel(
            name="EAPJourney",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("IN PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "eap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.eapdossier"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eapdossier",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.patient"
            ),
        ),
        migrations.CreateModel(
            name="CTJourney",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("IN PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("eligible", models.BooleanField(default=True)),
                ("ineligible_reason", models.TextField(blank=True, null=True)),
                ("outcome", models.TextField()),
                (
                    "ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ct"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="medical_condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.medicalcondition"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_person",
                to="api.person",
            ),
        ),
    ]
